### PR TITLE
fix #100 where oredict for platinum didnt apply to dust and below and fix #120

### LINKED ISSUE #100: [BUG]: uncraftable electrolytic core
### Describe the bug

Screenshot_20230226_195311

uncraftable recipe with the electrolytic core, this is caused by 90% of osmium/platinum items not getting platinum oredicts when the config is on, as if you have another mod adding platinum dust its fine

### To Reproduce

1. turn platinum oredict on
2. turn osmium oredict off
3. look at the electrolytic core in nei

### Expected behavior

for the "fire" to be platinum dust

### Mekanism Version

9.10.26

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Linux

### Name of modpack if applicable

_No response_

### Version of said modpack if applicable

_No response_

### Screenshots

_No response_

### The crash report in folder ./crash-reports (both server and client logs)

```shell
there is no crash
```

### Please provide the following other files

[Mekanism.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/10842583/Mekanism.txt)
[MekanismRecipes.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/10842584/MekanismRecipes.txt)

### LINKED ISSUE #120: [BUG]: About Chinese translation errors
### Describe the bug

When using the 'Mekanism Community Edition' in Chinese, I found a '=' in the Chinese display of the 'Thermal Distillation Valve', which should be an error caused by directly using the 'Mekanism' translation. I hope it can be corrected.

### To Reproduce

1. Go to ''

### Expected behavior

I hope to solve this localization problem

### Mekanism Version

9.10.28

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

_No response_

### Name of modpack if applicable

_No response_

### Version of said modpack if applicable

_No response_

### Screenshots

QQ截图20230525150609

### The crash report in folder ./crash-reports (both server and client logs)

```shell
No error reported
```

### Please provide the following other files

_No response_

### PR DESCRIPTION
**Pull request by maggi373**

### CODE REVIEW

File: src/main/java/mekanism/common/Mekanism.java [hunk 1]
```diff
@@ -1292,11 +1289,13 @@ public void registerOreDict()
 
 		for(Resource resource : Resource.values())
 		{
-			OreDictionary.registerOre("dust" + resource.getName(), new ItemStack(MekanismItems.Dust, 1, resource.ordinal()));
-			OreDictionary.registerOre("dustDirty" + resource.getName(), new ItemStack(MekanismItems.DirtyDust, 1, resource.ordinal()));
-			OreDictionary.registerOre("clump" + resource.getName(), new ItemStack(MekanismItems.Clump, 1, resource.ordinal()));
-			OreDictionary.registerOre("shard" + resource.getName(), new ItemStack(MekanismItems.Shard, 1, resource.ordinal()));
-			OreDictionary.registerOre("crystal" + resource.getName(), new ItemStack(MekanismItems.Crystal, 1, resource.ordinal()));
+			if (!(!mekce.OreDictOsmium && resource.getName() == "Osmium")) {
```
Comment (DrParadox7) [inline src/main/java/mekanism/common/Mekanism.java:1292]: Double Negative

**Review by DrParadox7 — APPROVED** [review]
